# 20721B2 firmware build 211
# patch entries used: 149 out of 256 elf patches, 58%
CY_PATCH_ENTRIES_BASE=149
# additional patch entries in these libraries:
#   8 in wiced_ble_connect_timing_lib.a
#   17 in wiced_audio_sink_lib.a
#   1 in average_rssi_lib.a
#   1 in sco_aud_hook_lib.a
#   50 in lr_cync_lib.a
#   5 in wiced_mem_lib.a
#   1 in i2s_aud_record_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   1 in wiced_uart_stop_bit_lib.a
#   1 in ia_aaclc_lib.a
#   7 in wiced_audio_source_lib.a
#   2 in wiced_app_watchdog_lib.a
# patch ram used: 28784 out of 64512 bytes, 44%
