# 20721B2 firmware build 167
# patch entries used: 119 out of 256 elf patches, 46%
CY_PATCH_ENTRIES_BASE=119
# additional patch entries in these libraries:
#   2 in wiced_app_watchdog_lib.a
#   1 in i2s_aud_record_lib.a
#   1 in wiced_uart_stop_bit_lib.a
#   4 in wiced_uart_raw_mode_lib.a
#   5 in wiced_audio_source_lib.a
#   5 in wiced_mem_lib.a
#   1 in ia_aaclc_lib.a
#   16 in wiced_audio_sink_lib.a
#   1 in sco_aud_hook_lib.a
#   1 in average_rssi_lib.a
#   50 in lr_cync_lib.a
# patch ram used: 22744 out of 64512 bytes, 35%
